import "./globals.css";

import type { Metadata } from "next";
import { Manrope } from "next/font/google";

import { ConvexClientProvider } from "@/providers/ConvexClientProviders";
import { cn } from "@/lib/utils";

const font = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en" 
      suppressHydrationWarning
      suppressContentEditableWarning
    >
      <body className={cn(font.className, "antialiased")}>
        <ConvexClientProvider>
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
